function [xb, yb] = block_boundary(blk, ib)

    xb = [blk.x{ib}(1:end-1,1); ...
        blk.x{ib}(end,1:end-1)'; ...
        blk.x{ib}(end:-1:2,end); ...
        blk.x{ib}(1,end:-1:2)'];

    yb = [blk.y{ib}(1:end-1,1); ...
        blk.y{ib}(end,1:end-1)'; ...
        blk.y{ib}(end:-1:2,end); ...
        blk.y{ib}(1,end:-1:2)'];

end
